version: '3.9'

services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - order-service
    volumes:
      - ./proto:/app/proto
    environment:
      - NODE_ENV=development

  order-service:
    build: ./order-service
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      - kafka
    volumes:
      - ./proto:/app/proto
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=orders_db
      - KAFKA_BROKER=kafka:9092

  processor-service:
    build: ./processor-service
    depends_on:
      - kafka
      - mongodb
    volumes:
      - ./proto:/app/proto
    environment:
      - MONGO_URI=mongodb://mongodb:27017/orders

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: orders_db
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
